image: and07/image-go-ci:latest

services:
  - docker:dind

stages:
- build
- test
#- lint
- deploy

#variables:
#  KUBECONFIG: /etc/deploy/config
#  REPOSITORY: ad1asia/tg-alert-bot
#  NAMESPACE: tg-alert-bot
#  TAG: ${CI_BUILD_REF_NAME}_${CI_BUILD_REF}
#  CONTAINER_IMAGE: docker.io/${REPOSITORY}:${CI_BUILD_REF_NAME}_${CI_BUILD_REF}
#  CONTAINER_IMAGE_LATEST: docker.io/${REPOSITORY}:latest

build:
  stage: build
  script:
    - docker logout
    - docker login -u $DOCKER_USER -p $DOCKER_PASS docker.io
    - make docker-push-ci

test:
  stage: test
  script:
    - make test

#lint:
#  stage: lint
#  script:
#    - make lint-full

deploy:
  stage: deploy
  script:
  - ansible-playbook playbook.yml --extra-vars "TG_API_KEY=$TG_API_KEY TG_CHAT_ID=$TG_CHAT_ID"
  tags:
    - deploy
